version: "3"
services:
  app:
    image: my-node-app
    ports:
      - "1337:1337" # Match the port your app runs oN
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_DIALECT: ${DB_DIALECT}
    depends_on:
      database:
        condition: service_healthy # Ensure the database service is healthy before starting this service
    command: >
      sh -c "echo 'MIGRATING DATA' &&
      npx sequelize-cli db:migrate && echo 'MIGRATION DONE' &&
      echo 'SEEDING DATA' && 
      npx sequelize-cli db:seed:all && echo 'SEEDING DONE' &&
      echo 'Starting up app via `npm run dev` script' &&
      npm run dev"

  database:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"  # Optional, if you need to access the DB externally
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]  # Check if PostgreSQL is ready to accept connections
      interval: 10s  # Perform the health check every 10 seconds
      retries: 5  # Number of consecutive failures before marking the container as unhealthy
      start_period: 1s  # Grace period before starting health checks
    

  